apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-ing
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "1"
spec:
  rules:
    - http:
        paths:
          - path: /staging/api
            pathType: Prefix
            backend:
              service:
                name: todo-backend-svc
                port:
                  number: 80
          - path: /staging
            pathType: Prefix
            backend:
              service:
                name: todo-app-svc
                port:
                  number: 80
