apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep

spec:
  replicas: 2
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: project/broadcaster
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: broadcaster-cm
                  key: env
            - name: NATS_HOST
              valueFrom:
                configMapKeyRef:
                  name: broadcaster-cm
                  key: nats_host
            - name: NATS_PORT
              valueFrom:
                configMapKeyRef:
                  name: broadcaster-cm
                  key: nats_port
            - name: TELEGRAM_URL
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secrets
                  key: telegram_url
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secrets
                  key: telegram_bot_token
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secrets
                  key: telegram_chat_id
            - name: TELEGRAM_THREAD_ID
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secrets
                  key: telegram_thread_id
