apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: project/todo-app
    newName: taas93/todo-app
    newTag: 5265c3a1-f684-419c-9454-0942d25caec3
  - name: project/todo-backend
    newName: taas93/todo-backend
    newTag: 8d02cb16-0c85-48be-a169-b36784b03ec2
  - name: project/broadcaster
    newName: taas93/broadcaster
    newTag: 07ffb4b3-d618-47c0-a191-4767dbce64b2
resources:
  - manifests
