apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: exercises/create-file
  newName: CREATE_FILE_IMAGE
- name: exercises/file-output
  newName: FILE_OUTPUT_IMAGE
- name: exercises/ping-pong
  newName: taas93/ping-pong
  newTag: 5e4cc753308a989c6fca12fab6e811793a2a4e59
resources:
- manifests
