apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: exercises/create-file
  newName: taas93/create-file
  newTag: 5e87a6e4a722e302e7aa3b4ff941b129a681bbcf
- name: exercises/file-output
  newName: taas93/file-output
  newTag: 5e87a6e4a722e302e7aa3b4ff941b129a681bbcf
- name: exercises/ping-pong
  newName: taas93/ping-pong
  newTag: 5e87a6e4a722e302e7aa3b4ff941b129a681bbcf
resources:
- manifests
