apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: exercises/create-file
  newName: taas93/create-file
  newTag: 2321910111e7b172a2c5178bd79e9e921aaec051
- name: exercises/file-output
  newName: taas93/file-output
  newTag: 2321910111e7b172a2c5178bd79e9e921aaec051
- name: exercises/ping-pong
  newName: taas93/ping-pong
  newTag: 2321910111e7b172a2c5178bd79e9e921aaec051
resources:
- manifests
