apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: exercises/create-file
  newName: taas93/create-file
  newTag: 6c8f05efc1ca6206da5e72e16e401a3dd03e836e
- name: exercises/file-output
  newName: taas93/file-output
  newTag: 6c8f05efc1ca6206da5e72e16e401a3dd03e836e
- name: exercises/ping-pong
  newName: taas93/ping-pong
  newTag: 6c8f05efc1ca6206da5e72e16e401a3dd03e836e
resources:
- manifests
