apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-cm
data:
  port: "3003"
  host: "0.0.0.0"
  database_host: "postgres-svc"
  database_name: "todos"
  database_port: "5432"
  nats_host: "my-nats"
  nats_port: "4222"
  env: "development"
