name: Production deployment

on:
  workflow_dispatch:
  push:
    paths:
      - "the_project/**"
    tags:
      - "*.*"

env:
  BRANCH: ${{ github.ref_name }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
  ENV: ${{ vars.ENV }}

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ env.DOCKER_USER }}"
          password: "${{ env.DOCKER_PASSWORD }}"

      # todo-app

      - name: Form todo-app image name
        run: echo "TODO_APP_IMAGE=$DOCKER_USER/todo-app:prod-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build and publish todo-app
        working-directory: the_project
        run: docker buildx build --tag $TODO_APP_IMAGE --push ./todo-app --build-arg ENV=$ENV

      # todo-backend

      - name: Form todo-backend image name
        run: echo "TODO_BACKEND_IMAGE=$DOCKER_USER/todo-backend:prod-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build and publish todo-backend
        working-directory: the_project
        run: docker buildx build --tag $TODO_BACKEND_IMAGE --push ./todo-backend --build-arg ENV=$ENV

      # broadcaster

      - name: Form broascaster image name
        run: echo "BROADCASTER_IMAGE=$DOCKER_USER/broadcaster:prod-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build and publish broascaster
        working-directory: the_project
        run: docker buildx build --tag $BROADCASTER_IMAGE --push ./broadcaster --build-arg ENV=$ENV

      # finalize

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update images on file
        working-directory: the_project/manifests/overlays/production
        run: |-
          kustomize edit set image project/todo-app=$TODO_APP_IMAGE
          kustomize edit set image project/todo-backend=$TODO_BACKEND_IMAGE
          kustomize edit set image project/broadcaster=$BROADCASTER_IMAGE

      - name: Commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: "the_project/manifests/overlays/production/kustomization.yaml"
          message: New version released ${{ github.sha }}
          new_branch: main
